// <auto-generated />
using System;
using HeroesCup.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace heroescupreloaded.Migrations
{
    [DbContext(typeof(HeroesCupDbContext))]
    [Migration("20230919105229_clagecategory")]
    partial class clagecategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

#pragma warning restore 612, 618
        }
    }
}
